/** Non-React templates, compiled through the parser into route modules. */
import { existsSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import type { Framework } from "./frameworks.js";
import type { AdoptChange, AdoptScan, TemplateFile } from "./types.js";
import {
  GENERATED_COMPONENTS,
  GENERATED_ROUTES,
  templateFiles,
} from "./scan.js";

function countNodes(nodes: readonly unknown[] = []): number {
  let total = 0;
  for (const node of nodes) {
    total += 1;
    const children = (node as { children?: unknown }).children;
    if (Array.isArray(children)) total += countNodes(children);
  }
  return total;
}

/** URL path a template file serves, or `undefined` when it is a plain component. */
export function templateRoute(
  file: string,
  framework: Framework,
): string | undefined {
  // Angular has no file-based routing convention: routes live in the router
  // module's TypeScript, which is not compiled here. Inventing a URL from a
  // component's filename would be a guess, so its components stay unmounted.
  if (framework === "angular") return undefined;
  const segments = file.split("/");
  const base = segments.pop()!;
  const stem = base.replace(/\.(svelte|vue|astro)$/, "");
  const rootIndex = segments.findIndex((s) => s === "routes" || s === "pages");

  if (stem.startsWith("+page")) {
    if (rootIndex === -1) return "/";
    const rest = segments
      .slice(rootIndex + 1)
      .filter((s) => !s.startsWith("("));
    return `/${rest.join("/")}`.replace(/\/$/, "") || "/";
  }
  if (rootIndex !== -1) {
    const rest = [...segments.slice(rootIndex + 1), stem].filter(
      (s) => !s.startsWith("("),
    );
    if (rest.at(-1) === "index") rest.pop();
    return `/${rest.join("/")}`.replace(/\/$/, "") || "/";
  }
  if (/^(app|App)$/.test(stem) && segments.length <= 1) return "/";
  return undefined;
}

export function generatedModule(route: string): string {
  const rest = route.replace(/^\//, "");
  return `${GENERATED_ROUTES}/${rest === "" ? "index" : rest}.tsx`;
}

/**
 * A template that compiles but maps to no URL still becomes a component module,
 * so the compiled IR is importable. Angular has no file-based routing at all, so
 * this is the whole of its output — mounting it stays the user's decision.
 */
export function componentModule(file: string): string {
  const slug = file
    .replace(/\.(svelte|vue|astro|ng)$/, "")
    .replace(/\.(component|ng)\.html$/, "")
    .replace(/[^a-zA-Z0-9/-]/g, "-");
  return `${GENERATED_COMPONENTS}/${slug}.tsx`;
}

/**
 * Compile every template through the crepuscularity frontend its filename
 * selects. A template that does not compile is recorded with the parser's own
 * message: unsupported constructs are hard errors, so nothing is silently
 * dropped from the page.
 */
export async function compileTemplates(
  projectDir: string,
  framework: Framework,
  globs: readonly string[],
): Promise<TemplateFile[]> {
  const { parseTemplate } = await import("@tschk/crepuscularity-wasm");
  const files = templateFiles(projectDir, globs);

  const templates: TemplateFile[] = [];
  const taken = new Set<string>();
  for (const file of files) {
    const route = templateRoute(file, framework);
    const entry: TemplateFile = { file, ok: false };
    if (route !== undefined && !taken.has(route)) {
      taken.add(route);
      entry.route = route;
    }
    try {
      const ir = parseTemplate(
        readFileSync(join(projectDir, file), "utf8"),
        file.split("/").pop()!,
      );
      entry.ok = true;
      entry.nodes = countNodes(ir.root ?? []);
      entry.ir = ir;
      entry.irVersion = ir.version;
      entry.generated =
        entry.route !== undefined
          ? generatedModule(entry.route)
          : componentModule(file);
    } catch (error) {
      entry.error = error instanceof Error ? error.message : String(error);
      delete entry.route;
    }
    templates.push(entry);
  }
  return templates;
}

/** Modules generated from the templates: IR in, React elements out. */
export function planTemplateRoutes(scan: AdoptScan): AdoptChange[] {
  const changes: AdoptChange[] = [];
  for (const template of scan.templates) {
    if (!template.generated) continue;
    const path = join(scan.projectDir, template.generated);
    const name = template.route ? "Route" : "Component";
    const contents = `// Generated by \`moonshine adopt\` from ${template.file}: crepuscularity parsed that template into View IR v${template.irVersion}. Re-run \`moonshine adopt --force\` after editing the template.
import { renderCrepusIr, type CrepusIr } from "@tschk/crepus-moonshine";

const ir = ${JSON.stringify(template.ir, null, 2)} as CrepusIr;

export default function ${name}() {
  return renderCrepusIr(ir);
}
`;
    const exists = existsSync(path);
    const alreadyApplied = exists && readFileSync(path, "utf8") === contents;
    const what = template.route
      ? `route ${template.route}`
      : "unmounted component";
    changes.push({
      file: template.generated,
      action: alreadyApplied ? "none" : exists ? "modify" : "create",
      details: alreadyApplied
        ? []
        : [
            `${what} renders ${template.file} (${template.nodes ?? 0} View IR nodes)`,
          ],
      summary: alreadyApplied
        ? "already generated"
        : `${exists ? "regenerated" : "generated"} ${what} from ${template.file}`,
      alreadyApplied,
      ...(alreadyApplied ? {} : { contents }),
    });
  }
  return changes;
}
