import 'dart:convert';

/// Lower a View IR map (decoded JSON) to a TypeScript module string.
///
/// The emitted file imports `renderCrepusIr` from `@tschk/crepus-moonshine`
/// and exports a default React component.
String emitTypeScript(
  Map<String, dynamic> ir, {
  String componentName = 'CrepusApp',
}) {
  final json = const JsonEncoder.withIndent('  ').convert(ir);
  return '''
/* Generated by moonshine_jaspr — do not edit by hand */
import { renderCrepusIr } from "@tschk/crepus-moonshine";
import type { CrepusIr } from "@tschk/crepus-moonshine";

const ir = $json as CrepusIr;

export default function $componentName() {
  return renderCrepusIr(ir);
}
''';
}

/// Convenience: parse a JSON string then emit TypeScript.
String emitTypeScriptFromJson(
  String json, {
  String componentName = 'CrepusApp',
}) {
  final decoded = jsonDecode(json);
  if (decoded is! Map<String, dynamic>) {
    throw ArgumentError('IR root must be a JSON object');
  }
  return emitTypeScript(decoded, componentName: componentName);
}
